name = "MVS+ Client"
author = "MVS+"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d827c6320053d187d4017e0ace164eb11b89790a8d5cb721e7dbf85261148df2"

[versions]
minecraft = "1.19.2"
quilt = "0.17.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
