name = "MVS+ Client"
author = "MVS+"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a3b8f96de9c4e54c8f8dfd72c74a3f8aaafbfc1952e1f8825e80090a470f8f9"

[versions]
minecraft = "1.19.2"
quilt = "0.17.1"
