name = "MVS+ Client"
author = "MVS+"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46fd7f293e6d8d163a183385f609345b71c3b1d808aca0f90552042c2bc9fcfe"

[versions]
minecraft = "1.19.2"
quilt = "0.17.3"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
