name = "MVS+ Client"
author = "MVS+"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "305aa267ad24278e91fdc9f50448684c3b6f36f63614693a585618401ecd7d57"

[versions]
minecraft = "1.19.2"
quilt = "0.17.2-beta.3"
